### PR TITLE
Use semver to check for compatible Node version. Use package.json engines prop too.

### LINKED ISSUE #309: Some more useful error message when using backlevel nodejs
### Description

Ranviermud requires a more up to date node.js than apt-get installs on a typical ubuntu 16.04 LTS:

ubuntu@ip-172-31-23-236:~/ranviermud$ node -v
v4.2.6
ubuntu@ip-172-31-23-236:~/ranviermud$ npm -v
3.5.2

This results in an ugly error:

ubuntu@ip-172-31-23-236:~/ranviermud$ ./ranvier
/home/ubuntu/ranviermud/src/Account.js:129
    const {
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/ranviermud/src/AccountManager.js:4:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

Instead of somewhere along the line seeing more clearly that, hey, idiot, no really when the requirement says "Node.js >= v7.1.0" it wasn't kidding.

### PR DESCRIPTION
**Pull request by seanohue**
Fixes #309

### CODE REVIEW

**Comment by seanohue** [comment]
Good call.

**Comment by seanohue** [comment]
Updated to pull in the version dynamically and fixed an error on my part. Thanks!

**Comment by seanohue** [comment]
Done! Good feedback.

**Comment by shawncplus** [comment]
The current LTS is 8.x so let's just go ahead and use this opportunity to set that in stone as the minimum req for Ranvier.

**Comment by seanohue** [comment]
Donezo.

**Pull request merged**
