### PR TITLE
Quest refactor. resolves #296

### LINKED ISSUE #296: RFC: Refactor Quest System
Currently quests have to be written in a javascript file which is a pretty terrible experience for builders that aren't also programmers.

## High level plans

Allow quests to be defined in a YAML file like items and npcs. This will allow for quests to be created entirely in Soma (assuming the required goal and reward type classes exist)

#### Rewards
Quest#reward should be an array of `QuestReward` objects that have `give` and `display` methods.

Example reward types

* CurrencyReward
* ItemReward(array items)
** if items is an array render ItemUtil.displayItem by splitting two item displays on \r\n, looping over Max(item 1 arr len, item 2 arr len), use '' 
* ExperienceReward
* ChoiceReward - A reward type that accepts an `array<Reward>` and will allow user to choose one of the rewards

#### Goals

Quest Goals should have the option to require completion in order and to only reveal subsequent goals when preceding goals are completed, e.g., travel to Room A, once that's done, Travel to Room B appears as the goal

#### Core changes

* `quests.js` should be replaced by `quests.yml`
* New bundle types: `quest-rewards` and `quest-goals`
* Update `BundleManager` to load in new reward and goal bundles, assign reward and goals to `QuestFactory`
* There will be some changes needed to `QuestFactory#create` for instantiating the goals and rewards
* `QuestGoal` should get a new static `bool validate(config)` method that is called during bundle load to halt server startup if there is a quest with a bad config

#### Bundle changes

* The `ranvier-quests` bundle will have to move the goals from `lib` to the new `quest-goals` bundle type
* `ranvier-areas` will have to rewrite the `quests.js` to the new format

### PR DESCRIPTION
**Pull request by shawncplus**
Quests are now defined in yaml just like items, npcs, and rooms. This allows builders to need to know how to code in order to create quests. Additionally, this makes it so Soma will be able to build quests as well. Pretty cool. An extra benefit of this is that Reward is now a codified type making it more resuable when you want to have a bunch of quests give a similar type of reward.

If you have created quests in the old system please try out this branch to test it and port your quests over.

### CODE REVIEW

**Comment by shawncplus** [comment]
@bostrt You seem to be the last one I saw working with the quest system, when you get a chance please test this branch with your quests.

**Comment by bostrt** [comment]
@shawncplus I can't seem to get ranvier started up. Below is from a fresh checkout of the quest-refactor branch with no changes yet:

```
# git status
On branch quest-refactor
Your branch is up-to-date with 'origin/quest-refactor'.
nothing to commit, working tree clean
# ./ranvier 
2018-01-07T19:21:10.732Z - info: START - Loading entities
2018-01-07T19:21:10.781Z - verbose: LOAD: BUNDLES
2018-01-07T19:21:10.783Z - verbose: LOAD: BUNDLE [debug-commands] START
2018-01-07T19:21:10.784Z - verbose: 	LOAD: Commands...
2018-01-07T19:21:10.809Z - verbose: 	ENDLOAD: Commands...
2018-01-07T19:21:10.810Z - verbose: ENDLOAD: BUNDLE [debug-commands]
2018-01-07T19:21:10.810Z - verbose: LOAD: BUNDLE [ranvier-areas] START
2018-01-07T19:21:10.811Z - verbose: 	LOAD: Areas...
2018-01-07T19:21:10.832Z - verbose: 		LOAD: Quests...
2018-01-07T19:21:10.841Z - verbose: 			Loading Quest [limbo:1]
2018-01-07T19:21:10.841Z - verbose: 			Loading Quest [limbo:2]
2018-01-07T19:21:10.842Z - verbose: 			Loading Quest [limbo:3]
2018-01-07T19:21:10.842Z - verbose: 		ENDLOAD: Quests...
2018-01-07T19:21:10.843Z - verbose: 		LOAD: Items...
2018-01-07T19:21:10.867Z - verbose: 			Loading Item Script [limbo:9] 9-ranvier-blade
/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:316
    for (const [eventName, listener] of Object.entries(scriptListeners)) {
                                               ^

TypeError: Object.entries is not a function
    at BundleManager.loadEntityScript (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:316:48)
    at items.forEach.item (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:253:14)
    at Array.forEach (native)
    at BundleManager.loadItems (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:243:11)
    at BundleManager.loadArea (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:211:12)
    at BundleManager.loadAreas (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:177:23)
    at BundleManager.loadBundle (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:94:25)
    at BundleManager.loadBundles (/home/user/code/ranviermud-newquest/ranviermud/src/BundleManager.js:52:14)
    at init (/home/user/code/ranviermud-newquest/ranviermud/ranvier:126:17)
    at Object.<anonymous> (/home/user/code/ranviermud-newquest/ranviermud/ranvier:160:1)

```

**Comment by shawncplus** [comment]
> TypeError: Object.entries is not a function

Looks like your node version is out of date

**Comment by bostrt** [comment]
> Looks like your node version is out of date

You are correct, I updated to Node 9.x and all good. I managed to get my local quest running with the new quests.yml; no issues found.

**Pull request merged**
