### PR TITLE
Fix craft list display.

### PR DESCRIPTION
**Pull request by thedandroid**

### CODE REVIEW

**Comment by shawncplus** [comment]
This doesn't look quite right but I may be wrong, will try it out shortly

**Comment by thedandroid** [comment]
Thought the same thing later after I was already away from my desk. I’ll test later when I get home.

**Comment by thedandroid** [comment]
Unless you beat me to it.

**Comment by shawncplus** [comment]
This is _technically_ correct but I'd rename the `items` variable to something like `categoryEntry`.

**Pull request merged**
