### PR TITLE
Improve help

### PR DESCRIPTION
**Pull request by seanohue**
Made it look better, and more extensive. Custom-rigged templating. Helpfiles for things besides commands. Consider adding `help all` or `help topics` to list all topics dynamically.

### CODE REVIEW

**Comment by seanohue** [comment]
oh god why do i keep doing this

**Comment by Xarcell** [comment]
I really appreciate what you do here. I'd hate to see this project die or get dusty.

**Comment by seanohue** [comment]
Thanks! Mostly I've been developing to a fork but github must really want
to submit a PR to this branch. I'll probably do so soon (not anything so
massive though).


Sean O'Donohue
--
*Web Application Developer*
*GM NGI Onsite Team*


"The brave belong where they decide." *- *Iain M. Banks*, Consider Phlebas*

**Comment by chrisciampoli** [comment]
I’ve not really contributed, but I just want to also say thank you for doing this project.  I’ve played MUDs since the early 90’s, and having to go back and work with C or C++ for things, is just cumbersome.  It really is amazing the work you’ve been doing.

Regards,

Christopher Ciampoli
chrisciampoli@gmail.com
Software Engineer
SCTR Services

**Pull request closed without merging**
