### PR TITLE
Say command

### PR DESCRIPTION
**Pull request by seanohue**
This command allows players to say a message which will only be seen by players who are in the same room.

### CODE REVIEW

**Comment by shawncplus** [comment]
lots of neat pull requests, I'll try to merge them tonight. I'm interested in how you found the project and what you're using it for. I saw this tweet https://twitter.com/tomdale/status/660893508715339776 and assumed that was the source of the new contributors, maybe that's not the case though

**Comment by seanohue** [comment]
@shawncplus I found the project about 5-6 months ago when I started learning JavaScript because I enjoy MUDs and wanted to see if there were any written purely in JS. I literally just searched for MUDs written in JS on Github.

RanvierMUD is the only one I found, so I started poking at it and trying to contribute. Mostly I've just been using it for fun and for learning but maybe someday I'll host an actual fleshed-out MUD server using it.

I have all of the new PRs merged in on my branch and since some of them depend on each other in funny ways I also coded some bits to make them all gel together (for example, merging in descriptions and the character command means that typing `char` will cause an error). I can submit another PR to fix that once they're merged, or submit a giant kitchen sink PR, or add error handling.

Thanks!

**Comment by seanohue** [comment]
I also posted a reddit thread about it recently, since I thought it was a cool project and hoped it'd attract some more interest: https://www.reddit.com/r/MUD/comments/3ryy4l/ranviermud_a_lightweight_mud_engine_being/

**Comment by marado** [comment]
@shawncplus I bumped into this project (and my interest in it comes) from a discussion in another project: https://github.com/amnuts/Amnuts/issues/4 . Glad to see this project active!

**Comment by seanohue** [comment]
@shawncplus this one plays well with all of the previous PRs.

**Comment by seanohue** [comment]
Closed because it's just duplicating the say command.

**Pull request closed without merging**
