### PR TITLE
Update README.mkd

### PR DESCRIPTION
**Pull request by MarchosiasM**
Hey, I just changed the windows install command in the readme file

### CODE REVIEW

**Comment by shawncplus** [comment]
I don't have a windows machine to test this on, anyone else wanna take a second look?

**Comment by rdwoodring** [comment]
I just pulled it down the other day on windows. Might have a chance to try it today or tomorrow

**Comment by MarchosiasM** [comment]
Also edited the motd

**Comment by shawncplus** [comment]
I'm going to close this PR so the MOTD change can be made separately from the, now unnecessary, README update

**Pull request closed without merging**
