### PR TITLE
Appraise mob

### PR DESCRIPTION
**Pull request by seanohue**
This command lets a user 'appraise' an NPC. It returns a string based on how the NPC's level matches up to the player's level.

### CODE REVIEW

**Comment by marado** [comment]
You're pull requesting the wrong thing: notice, for instance, the 65914a7 commit.

**Comment by seanohue** [comment]
Ah, I'll remove that part. Thanks. There was a small note in the docs that
I meant to leave in, though.


Sean O'Donohue
--
*Web Application Developer*

*Apprentice Class Gamma*
*Onsite Team*

**Comment by seanohue** [comment]
I removed the changes to the docs in a later commit, check the changed files. Good observation, though.

**Comment by seanohue** [comment]
This one should also be okay to merge in.

**Comment by seanohue** [comment]
@shawncplus This one plays nicely with the previous pull request for viewing attributes.

**Pull request closed without merging**
