### PR TITLE
Get all

### PR DESCRIPTION
**Pull request by seanohue**
Now, typing "get all" will allow you to pick up all of the items in the room as long as you are not in combat, and have room in your inventory.

### CODE REVIEW

**Comment by Xarcell** [comment]
Thanks for this.

**Comment by seanohue** [comment]
@Xarcell Thanks. Any suggestions on what to tackle next?

**Comment by Xarcell** [comment]
It's hard to say. There are things I'd like to see, but that doesn't mean everyone would want it. Here are a few I can think of off the top of my head: 

1.| Optional 3 different room descriptions for different times of the day, such as dawn/dusk, day, and night.

2.| Optional 2 additional different room descriptions based on racial attributes, some see in the dark and are blinded by light, while others are blind in the dark, but see in the light. If combined with number one, it would total 5 room descriptions per room(optional of course, not every room needs additional descriptions, such as the inside of a tavern.

3.| Throwing = the ability to throw items for damage and recover some those items, but not always.

4.| Item Use Breakage = either through complex formula or just set number of uses.

5.| Guild = accept or deny other players into the guild. Guild houses restrict access to members only.

**Comment by seanohue** [comment]
Nice ideas! I am also trying to work on shops but am unable to fathom how I'd set it up in YML, or if that'd even be the place to start. And related to point #5, I also want to add admin/wizard abilities to be able to make changes in game. Adding guild leader/member permissions would be similar. Another related story could be locked doors -- you can only enter with a certain item in your inventory. 

Thanks for the ideas, @Xarcell

**Comment by shawncplus** [comment]
@seanohue my original goal for in game changes was the web editor here https://github.com/shawncplus/ranvier-webbuilder (Which is equally wicked out of date). I really hate in-game OLEs they're always clunky.

Regarding shops: off the top of my head would just be something like

NPC YML

    -
      vnum: 7
      room: 4
      short_description:
        en: 'A shopkeeper stands at the counter'
      shop: 1
      behaviors: "shopkeeper"

object YML

    - &longsword
        vnum: 1
        short_description:
            en: "a longsword"
            es: "A rapier"
        keywords:
            en: [ "longsword", "sword", "long" ]
            es: [ "rapier", "sword" ]

shop YML (would need a new shops/ dir and data load)

shop/1.yml

    - &newbieshop
      vnum: 1
      pricing_calc: " script to modify price based on game state
        reputation: guardians " imaginary pricing script that takes a faction and gives a % discount based on standing
        quest: 12 " discount for having completed given quest
        class: warrior " discount for given class
      purchase: true " whether players can sell items here
      items:
        -
          item: 1
          price: 100
          inventory: 3 " count in the shop before it runs out, restock on respawn
          multisell: true " alternative to inventory, stock never depletes

**Comment by seanohue** [comment]
@shawncplus I never thought of having both a shop entity and a shopkeeper entity, but that makes perfect sense like that. I also like the various flags and idea of having some shops sell items for more than others.  The shopkeeper behavior script and the buy/sell/list commands would have to all be programmed to play well together, I assume? I still don't fully understand how the items and npcs work and how the MUD grabs all of this information from the YML, but this is a good starting point, thanks.

As an aside, this PR doesn't break any of the previous ones I've submitted.

**Comment by seanohue** [comment]
@shawncplus Also might hack away on a tool for making in-game changes, but probably not that one since I have zero experience with ExtJS. Maybe Angular or something similar.

**Comment by shawncplus** [comment]
@seanohue yeah, please don't bother with that old crap :yum: With that said you can probably copy/paste all of the API stuff that the plugin uses and just rebuild the frontend

**Comment by seanohue** [comment]
@shawncplus Gotcha. Related to that -- is there a copyover function??

**Comment by shawncplus** [comment]
@seanohue there's a really terrible hotboot command that's usable from the server exe while it's running but no in-game command to execute it

**Pull request closed without merging**
