### PR TITLE
Improved look

### PR DESCRIPTION
**Pull request by seanohue**
Players can now look into adjacent rooms. They can see the title of the room and the description, but not the exits, players, NPCs, or items -- that is by design but could easily be changed.

Players can also look at other players and their own character. It'll say their name and a description, which is blank by default for the time being.

### CODE REVIEW

**Comment by seanohue** [comment]
The massive amount of whitespace changes are due to a difference in the amount of spaces used for tabs by my editor. I can fix it if it's an issue.

**Comment by Xarcell** [comment]
Sweet. Thanks for your contributions to this project.

**Comment by seanohue** [comment]
Update:

Made it so that players can look at other players. It'll say their name and a description, which is blank by default for the time being.

**Comment by seanohue** [comment]
Oh hey, now players can look at themselves, too. I'll be submitting a pull request so they can change their description as well, at some point.

**Comment by seanohue** [comment]
The last feature I added to this PR is a bit buggy, it seems that looking at your own character causes the description to be displayed twice. Strange.

**Comment by seanohue** [comment]
I fixed all issues for this PR.

**Comment by seanohue** [comment]
Players can now see the worn/wielded equipment of their characters or other player characters by using "look". @shawncplus @Xarcell

**Comment by Xarcell** [comment]
Awesome. Thanks.

**Comment by shawncplus** [comment]
@seanohue How many of these pull requests are you sure enough in that I can safely just click click click and merge them in?

**Comment by seanohue** [comment]
Each of them will work fine individually -- but the help command, for
example, won't have helpfiles for some of the new commands. It's been a
while since I've looked at any of this code so I'm not sure if there are
any breaking bugs anymore but I can take a look tonight/tomorrow.

Another alternative is that I can just submit a kitchen sink PR with all of
the new changes and some additional things (such as the aforementioned
helpfiles).


Sean O'Donohue
--
*Web Application Developer*

*Apprentice Class Gamma*
*Onsite Team*

**Comment by seanohue** [comment]
@shawncplus This one should also work out fine. I'm glad I got to work on a project where "Add nudity string" was a legitimate commit message.

**Comment by seanohue** [comment]
@shawncplus Confirmed that this one plays well with all previous PRs

**Pull request closed without merging**
