### PR TITLE
Multiple item slots

### LINKED ISSUE #249: Allow items to be equipped in multiple slots.
### Description

Example: You want to implement the ability to hold two items at once, one "wielded" and one "offhand". Currently, the `Item` class only allows for a single `slot` to be described, as a string. So if I have a candlestick that I equip and it goes into the 'wielded' slot, and then I try to equip a pitchfork, I will receive an error message telling me I cannot hold both. One potential solution is to allow item.slot to be defined as either a single slot (a string) or multiple slots (an array of strings). If it has multiple defined slots, then equip can do one of two things:
1) Try each of the slots in order until it finds an empty one, or throw an error if it does not find an open slot.
2) Take an optional second argument `equip pitchfork offhand` to specify an equipment slot. If the specified slot is not included in the pitchfork's array of slots (such as `equip pitchfork sandwich`), then throw an error, otherwise try to equip the item in that slot (succeeding or failing as normal).

### Expected outcome

Items can have multiple equippable slots.
Trying to equip an item with multiple equippable slots will try the slots in order until finding an open one or failing.
You can specify a slot to attempt to equip the item in.

### Actual outcome

Items only have one slot and there can only be one equipped item per slot.

### Steps to reproduce

Try creating an item with multiple slots. You can't do it. I double-dare you.

### Version of Ranvier
v1.1.1

### PR DESCRIPTION
**Pull request by seanohue**
Resolves #249 .

The `slot` property in each items YAML definition can now be a string or array of strings.
The appropriate `EquipError` is thrown if all of the listed slots are occupied by equipped items.

### CODE REVIEW

**Comment by shawncplus** [comment]
This LGTM at the moment, were you still working on this or is it ready to go as is?

**Comment by seanohue** [comment]
Yes, though as discussed in the slack, this only implements an either/or relationship between the list of slots. So, I can have an individual item that is wearable in two slots, but i can't make an item, for example, `pair of magical gauntlets` that covers both the `left hand` and `right hand` slots.

**Comment by shawncplus** [comment]
I think the unopinionated approach is to make the equip command _require_ the slot argument. That way the `equip` command can be the one that's opinionated about what happens

**Comment by seanohue** [comment]
Agreed, will rework this to have the core be largely un-opinionated.

**Comment by marcelomoreli** [comment]
Is this still on-going?

**Comment by shawncplus** [comment]
I think I'm going to close this PR, the conclusion that was arrived at was that the core `equip()` command shouldn't look at `item.slot` directly, instead it should take the slot as an argument and the `slot` property should be removed from item. That way it's up to the command to decide what to pass `equip()` and how.

**Pull request closed without merging**
