### PR TITLE
Tell command

### PR DESCRIPTION
**Pull request by seanohue**
Noticed there wasn't a "tell" command, figured this could be useful to some.

### CODE REVIEW

**Comment by Xarcell** [comment]
There are alot of commands I'd like to see. I can post a few tomorrow if your interested?

**Comment by Xarcell** [comment]
One thing I noticed by looking at the code is that the audience doesn't see anything. For example: Sean tells Xarcell blah blah blah. I noticed the same with the give command. Shouldn't the audience(people in the room) also see what Sean is giving Xarcell?

**Comment by shawncplus** [comment]
@Xarcell tell being silent makes sense, that's the purpose of a tell but I agree with give being "loud". Though it brings up the point of having configurable spam filters so players can mute loud commands not targeted at or by them.

**Comment by seanohue** [comment]
@Xarcell Basically, what @shawncplus said -- though, I'll add something for 3rd parties for the 'give' command. Tell is more for one on one OOC communication. They don't even need to be in the same room. Whisper is for in character conversation, and the third party can see that something is being whispered.

**Comment by Xarcell** [comment]
@seanohue ah, I didn't realize tell was a OOC communication.

**Comment by seanohue** [comment]
@Xarcell I've usually seen it used as an inter-player messaging system, like a private message. I guess whether it's OOC or not depends on the MUD, but it's a way to communicate with anyone online regardless of if they are in the same room or not.

**Comment by Xarcell** [comment]
I'm glad you added it. Only thing I worry about is the role playing aspect of it though. In Gemstone III, you needed an crystal amulet that you had to rub it to activate for it 60 seconds in order to communicate private messages or default sales channel. If you sent someone a PM, but your amulet wasn't activated, it would glow as a indicator you had a PM. Then you'd rub it to see you PM. Or something like that, it's been awhile since I played.

**Comment by shawncplus** [comment]
This is just my personal opinion on it since MUDders have different preferences but I prefer function over form and a lot of MUDs that are RP heavy tend to go the other way. There's a reason I made the skill system instantly grant skills at level up with no percentage system or practices, because it's F'ing annoying and gets in the way of the actually fun part of the game. At the same time one of the reasons it's so flexible is because I know, as I said, every MUDder has a different preference.

So as a preference I prefer to have zero-effort OOC utilities (tell/help/newbie/chat) instead of trying to shoehorning RP into it. Imagine if help files required you to sacrifice an item to a demon of knowledge or something, yeah it'd be awesome for RP but _horrible_ for actual usability.

**Comment by seanohue** [comment]
@shawncplus exactly, I figured this was the most 'lightweight' way of doing it, since that's the aim of the project, and the tell command could easily be removed/edited now that it's there in skeletal form.

**Comment by seanohue** [comment]
@xarcell Also, I'd be interested in any ideas you have.

**Comment by seanohue** [comment]
Closed because it's just duplicating the tell channel.

**Pull request closed without merging**
